### PR TITLE
Fix interaction render with inputState

### PR DESCRIPTION
**Pull request by Il9**
Summary - Modified to use a hook that takes shape conversion helper functions, propagates changes to the host, returns an interaction state.

InteractionResponse => InteractionState

interactionStateEncoder - inputState => InteractionState
interactionStateDecoder - InteractionState => inputState

### CODE REVIEW

**Comment by ragingwind** [comment]
@Il9 Can you squash commits to review the final changes? It's easy to follow the changes step by step, but it's already been addressed in recent changes.

**Comment by Il9** [comment]
@ragingwind 
I've been trying to squash the parts that have changed the most, but I'm not very good at it because the crashes are hard to spot.

Look except for this commit
 - Remove InteractionResponseContextProvider

**Comment by ragingwind** [comment]
@Il9 ok don't worry. I will take a look on the local

**Comment by ragingwind** [comment]
Great, I like the changes

**Pull request merged**
