### PR TITLE
Implement hotspot interaction

### PR DESCRIPTION
**Pull request by Il9**
#36

### CODE REVIEW

**Comment by disjukr** [comment]
please fix the type error

스크린샷 2021-11-23 오후 7 25 34

스크린샷 2021-11-23 오후 7 25 08

**Comment by disjukr** [comment]
Please refer to this commit https://github.com/riiid/qtikit/commit/82f7367f358ad990ff878df2bd4410b5870dc776

**Comment by Il9** [comment]
@disjukr 
Done.
I also remove not necessary userInput type in OrderInteraction

**Comment by disjukr** [comment]
스크린샷 2021-11-23 오후 9 27 28

I hope this prop is not `any` type

**Comment by Il9** [comment]
@disjukr 
I will fix on another branch

**Review by disjukr — APPROVED** [review]

**Pull request merged**
